export const IONET_MODULE_OPTIONS = Symbol('IONET_MODULE_OPTIONS');
export const IONET_BAR_SKELETON = Symbol('IONET_BAR_SKELETON');
export const IONET_HTTP_SERVER = Symbol('IONET_HTTP_SERVER');
export const IONET_WS_SERVER = Symbol('IONET_WS_SERVER');
export const IONET_REDIS_CLIENT = Symbol('IONET_REDIS_CLIENT');
export const IONET_ACTIONS = Symbol('IONET_ACTIONS');
