import { type ActionCommandInfo } from './action-scanner.js';
import { type CodeGenerator } from './typescript-generator.js';

export class CSharpCodeGenerator implements CodeGenerator {
  readonly language = 'C#';
  readonly fileExtension = '.cs';

  generate(actions: ActionCommandInfo[]): string {
    const lines: string[] = [
      '// Auto-generated by @nbb-ionet/extension-codegen',
      '// DO NOT EDIT MANUALLY',
      '',
      'namespace Ionet.Generated',
      '{',
      '    public static class Commands',
      '    {',
    ];

    for (const action of actions) {
      lines.push(`        public static class ${action.controllerName}`);
      lines.push('        {');
      lines.push(`            public const int Cmd = ${action.cmd};`);

      for (const method of action.methods) {
        const constName = this.toPascalCase(method.methodName);
        lines.push(`            public const int ${constName} = ${method.subCmd};`);
      }

      lines.push('        }');
      lines.push('');
    }

    lines.push('    }');
    lines.push('');

    for (const action of actions) {
      for (const method of action.methods) {
        const className = `${action.controllerName}${this.toPascalCase(method.methodName)}Request`;
        lines.push(`    public class ${className}`);
        lines.push('    {');
        lines.push(`        public int Cmd { get; set; } = ${action.cmd};`);
        lines.push(`        public int SubCmd { get; set; } = ${method.subCmd};`);
        lines.push(`        public ${this.mapType(method.parameterTypes[0])} Data { get; set; }`);
        lines.push('    }');
        lines.push('');
      }
    }

    for (const action of actions) {
      for (const method of action.methods) {
        const className = `${action.controllerName}${this.toPascalCase(method.methodName)}Response`;
        lines.push(`    public class ${className}`);
        lines.push('    {');
        lines.push(`        public int Cmd { get; set; } = ${action.cmd};`);
        lines.push(`        public int SubCmd { get; set; } = ${method.subCmd};`);
        lines.push(`        public ${this.mapType(method.returnType)} Data { get; set; }`);
        lines.push('    }');
        lines.push('');
      }
    }

    lines.push('}');

    return lines.join('\n');
  }

  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  private mapType(tsType: string): string {
    const typeMap: Record<string, string> = {
      'string': 'string',
      'number': 'double',
      'boolean': 'bool',
      'bigint': 'long',
      'void': 'object',
    };
    return typeMap[tsType] ?? 'object';
  }
}
