import { type ActionCommandInfo } from './action-scanner.js';
import { type CodeGenerator } from './typescript-generator.js';

export class GDScriptCodeGenerator implements CodeGenerator {
  readonly language = 'GDScript';
  readonly fileExtension = '.gd';

  generate(actions: ActionCommandInfo[]): string {
    const lines: string[] = [
      '# Auto-generated by @nbb-ionet/extension-codegen',
      '# DO NOT EDIT MANUALLY',
      '',
      'extends Node',
      'class_name Commands',
      '',
    ];

    for (const action of actions) {
      lines.push(`const ${action.controllerName}_CMD = ${action.cmd}`);

      for (const method of action.methods) {
        const constName = method.methodName.toUpperCase();
        lines.push(`const ${action.controllerName}_${constName} = ${method.subCmd}`);
      }

      lines.push('');
    }

    lines.push('');
    lines.push('# Request/Response classes');
    lines.push('');

    for (const action of actions) {
      for (const method of action.methods) {
        const className = `${action.controllerName}${this.toPascalCase(method.methodName)}Request`;
        lines.push(`class ${className}:`);
        lines.push(`    var cmd: int = ${action.cmd}`);
        lines.push(`    var sub_cmd: int = ${method.subCmd}`);
        lines.push(`    var data = null`);
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
