import { type ActionCommandInfo } from './action-scanner.js';
import { type CodeGenerator } from './typescript-generator.js';

export class LuaCodeGenerator implements CodeGenerator {
  readonly language = 'Lua';
  readonly fileExtension = '.lua';

  generate(actions: ActionCommandInfo[]): string {
    const lines: string[] = [
      '-- Auto-generated by @nbb-ionet/extension-codegen',
      '-- DO NOT EDIT MANUALLY',
      '',
      'local Commands = {}',
      '',
    ];

    for (const action of actions) {
      lines.push(`Commands.${action.controllerName} = {`);
      lines.push(`    cmd = ${action.cmd},`);

      for (const method of action.methods) {
        const constName = method.methodName;
        lines.push(`    ${constName} = ${method.subCmd},`);
      }

      lines.push('}');
      lines.push('');
    }

    lines.push('');
    lines.push('-- Request/Response constructors');
    lines.push('');

    for (const action of actions) {
      for (const method of action.methods) {
        const funcName = `new${action.controllerName}${this.toPascalCase(method.methodName)}Request`;
        lines.push(`function Commands.${funcName}(data)`);
        lines.push(`    return {`);
        lines.push(`        cmd = ${action.cmd},`);
        lines.push(`        subCmd = ${method.subCmd},`);
        lines.push(`        data = data`);
        lines.push(`    }`);
        lines.push('end');
        lines.push('');
      }
    }

    lines.push('return Commands');

    return lines.join('\n');
  }

  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
