import { type ActionCommandInfo } from './action-scanner.js';

export interface CodeGenerator {
  generate(actions: ActionCommandInfo[]): string;
  readonly language: string;
  readonly fileExtension: string;
}

export class TypeScriptCodeGenerator implements CodeGenerator {
  readonly language = 'TypeScript';
  readonly fileExtension = '.ts';

  generate(actions: ActionCommandInfo[]): string {
    const lines: string[] = [
      '// Auto-generated by @nbb-ionet/extension-codegen',
      '// DO NOT EDIT MANUALLY',
      '',
      'export const Commands = {',
    ];

    for (const action of actions) {
      lines.push(`  ${action.controllerName}: {`);
      lines.push(`    cmd: ${action.cmd},`);

      for (const method of action.methods) {
        const constName = this.toCamelCase(method.methodName);
        lines.push(`    ${constName}: ${method.subCmd},`);
      }

      lines.push('  },');
    }

    lines.push('} as const;');
    lines.push('');

    for (const action of actions) {
      for (const method of action.methods) {
        const interfaceName = `${action.controllerName}${this.toPascalCase(method.methodName)}Request`;
        lines.push(`export interface ${interfaceName} {`);
        lines.push(`  cmd: ${action.cmd};`);
        lines.push(`  subCmd: ${method.subCmd};`);
        lines.push(`  data: ${method.parameterTypes[0] ?? 'unknown'};`);
        lines.push('}');
        lines.push('');
      }
    }

    for (const action of actions) {
      for (const method of action.methods) {
        const interfaceName = `${action.controllerName}${this.toPascalCase(method.methodName)}Response`;
        lines.push(`export interface ${interfaceName} {`);
        lines.push(`  cmd: ${action.cmd};`);
        lines.push(`  subCmd: ${method.subCmd};`);
        lines.push(`  data: ${method.returnType};`);
        lines.push('}');
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  private toCamelCase(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }

  private toPascalCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
